import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by fumadocs/source tooling.
    ".source/**",
    // Consumer-targeted shadcn registry sources are validated by `shadcn build`.
    "registry/**",
    // Standalone Bun package with its own dependencies and typecheck.
    "services/provider/**",
  ]),
]);

export default eslintConfig;
